/**
 * Every country with its calling code and phone digit grouping
 * (e.g. [3, 3, 4] means 214-555-1234). Generated from libphonenumber-js metadata.
 */
export type CountryPhone = {
  iso: string;
  name: string;
  dial: string;
  groups: number[];
};

export const countries: CountryPhone[] = [
  { iso: "AF", name: "Afghanistan", dial: "+93", groups: [2, 3, 4] },
  { iso: "AX", name: "Åland Islands", dial: "+358", groups: [2, 7] },
  { iso: "AL", name: "Albania", dial: "+355", groups: [2, 3, 4] },
  { iso: "DZ", name: "Algeria", dial: "+213", groups: [3, 2, 2, 2] },
  { iso: "AS", name: "American Samoa", dial: "+1", groups: [3, 3, 4] },
  { iso: "AD", name: "Andorra", dial: "+376", groups: [3, 3] },
  { iso: "AO", name: "Angola", dial: "+244", groups: [3, 3, 3] },
  { iso: "AI", name: "Anguilla", dial: "+1", groups: [3, 3, 4] },
  { iso: "AG", name: "Antigua & Barbuda", dial: "+1", groups: [3, 3, 4] },
  { iso: "AR", name: "Argentina", dial: "+54", groups: [1, 2, 4, 4] },
  { iso: "AM", name: "Armenia", dial: "+374", groups: [2, 6] },
  { iso: "AW", name: "Aruba", dial: "+297", groups: [3, 4] },
  { iso: "AC", name: "Ascension Island", dial: "+247", groups: [5] },
  { iso: "AU", name: "Australia", dial: "+61", groups: [3, 3, 3] },
  { iso: "AT", name: "Austria", dial: "+43", groups: [3, 6] },
  { iso: "AZ", name: "Azerbaijan", dial: "+994", groups: [2, 3, 2, 2] },
  { iso: "BS", name: "Bahamas", dial: "+1", groups: [3, 3, 4] },
  { iso: "BH", name: "Bahrain", dial: "+973", groups: [4, 4] },
  { iso: "BD", name: "Bangladesh", dial: "+880", groups: [4, 6] },
  { iso: "BB", name: "Barbados", dial: "+1", groups: [3, 3, 4] },
  { iso: "BY", name: "Belarus", dial: "+375", groups: [2, 3, 2, 2] },
  { iso: "BE", name: "Belgium", dial: "+32", groups: [3, 2, 2, 2] },
  { iso: "BZ", name: "Belize", dial: "+501", groups: [3, 4] },
  { iso: "BJ", name: "Benin", dial: "+229", groups: [2, 2, 2, 2, 2] },
  { iso: "BM", name: "Bermuda", dial: "+1", groups: [3, 3, 4] },
  { iso: "BT", name: "Bhutan", dial: "+975", groups: [2, 2, 2, 2] },
  { iso: "BO", name: "Bolivia", dial: "+591", groups: [8] },
  { iso: "BA", name: "Bosnia & Herzegovina", dial: "+387", groups: [2, 3, 3] },
  { iso: "BW", name: "Botswana", dial: "+267", groups: [2, 3, 3] },
  { iso: "BR", name: "Brazil", dial: "+55", groups: [2, 5, 4] },
  {
    iso: "IO",
    name: "British Indian Ocean Territory",
    dial: "+246",
    groups: [3, 4],
  },
  { iso: "VG", name: "British Virgin Islands", dial: "+1", groups: [3, 3, 4] },
  { iso: "BN", name: "Brunei", dial: "+673", groups: [3, 4] },
  { iso: "BG", name: "Bulgaria", dial: "+359", groups: [2, 3, 3] },
  { iso: "BF", name: "Burkina Faso", dial: "+226", groups: [2, 2, 2, 2] },
  { iso: "BI", name: "Burundi", dial: "+257", groups: [2, 2, 2, 2] },
  { iso: "KH", name: "Cambodia", dial: "+855", groups: [2, 3, 3] },
  { iso: "CM", name: "Cameroon", dial: "+237", groups: [1, 2, 2, 2, 2] },
  { iso: "CA", name: "Canada", dial: "+1", groups: [3, 3, 4] },
  { iso: "CV", name: "Cape Verde", dial: "+238", groups: [3, 2, 2] },
  { iso: "BQ", name: "Caribbean Netherlands", dial: "+599", groups: [3, 4] },
  { iso: "KY", name: "Cayman Islands", dial: "+1", groups: [3, 3, 4] },
  {
    iso: "CF",
    name: "Central African Republic",
    dial: "+236",
    groups: [2, 2, 2, 2],
  },
  { iso: "TD", name: "Chad", dial: "+235", groups: [2, 2, 2, 2] },
  { iso: "CL", name: "Chile", dial: "+56", groups: [1, 4, 4] },
  { iso: "CN", name: "China", dial: "+86", groups: [3, 4, 4] },
  { iso: "CX", name: "Christmas Island", dial: "+61", groups: [3, 3, 3] },
  {
    iso: "CC",
    name: "Cocos (Keeling) Islands",
    dial: "+61",
    groups: [3, 3, 3],
  },
  { iso: "CO", name: "Colombia", dial: "+57", groups: [3, 7] },
  { iso: "KM", name: "Comoros", dial: "+269", groups: [3, 2, 2] },
  { iso: "CG", name: "Congo - Brazzaville", dial: "+242", groups: [2, 3, 4] },
  { iso: "CD", name: "Congo - Kinshasa", dial: "+243", groups: [3, 3, 3] },
  { iso: "CK", name: "Cook Islands", dial: "+682", groups: [2, 3] },
  { iso: "CR", name: "Costa Rica", dial: "+506", groups: [4, 4] },
  { iso: "CI", name: "Côte d’Ivoire", dial: "+225", groups: [2, 2, 2, 4] },
  { iso: "HR", name: "Croatia", dial: "+385", groups: [2, 3, 4] },
  { iso: "CU", name: "Cuba", dial: "+53", groups: [1, 7] },
  { iso: "CW", name: "Curaçao", dial: "+599", groups: [1, 3, 4] },
  { iso: "CY", name: "Cyprus", dial: "+357", groups: [2, 6] },
  { iso: "CZ", name: "Czechia", dial: "+420", groups: [3, 3, 3] },
  { iso: "DK", name: "Denmark", dial: "+45", groups: [2, 2, 2, 2] },
  { iso: "DJ", name: "Djibouti", dial: "+253", groups: [2, 2, 2, 2] },
  { iso: "DM", name: "Dominica", dial: "+1", groups: [3, 3, 4] },
  { iso: "DO", name: "Dominican Republic", dial: "+1", groups: [3, 3, 4] },
  { iso: "EC", name: "Ecuador", dial: "+593", groups: [2, 3, 4] },
  { iso: "EG", name: "Egypt", dial: "+20", groups: [2, 8] },
  { iso: "SV", name: "El Salvador", dial: "+503", groups: [4, 4] },
  { iso: "GQ", name: "Equatorial Guinea", dial: "+240", groups: [3, 3, 3] },
  { iso: "ER", name: "Eritrea", dial: "+291", groups: [1, 3, 3] },
  { iso: "EE", name: "Estonia", dial: "+372", groups: [4, 4] },
  { iso: "SZ", name: "Eswatini", dial: "+268", groups: [4, 4] },
  { iso: "ET", name: "Ethiopia", dial: "+251", groups: [2, 3, 4] },
  { iso: "FK", name: "Falkland Islands", dial: "+500", groups: [5] },
  { iso: "FO", name: "Faroe Islands", dial: "+298", groups: [2, 2, 2] },
  { iso: "FJ", name: "Fiji", dial: "+679", groups: [3, 4] },
  { iso: "FI", name: "Finland", dial: "+358", groups: [2, 7] },
  { iso: "FR", name: "France", dial: "+33", groups: [1, 2, 2, 2, 2] },
  { iso: "GF", name: "French Guiana", dial: "+594", groups: [3, 2, 2, 2] },
  { iso: "PF", name: "French Polynesia", dial: "+689", groups: [2, 2, 2, 2] },
  { iso: "GA", name: "Gabon", dial: "+241", groups: [2, 2, 2, 2] },
  { iso: "GM", name: "Gambia", dial: "+220", groups: [3, 4] },
  { iso: "GE", name: "Georgia", dial: "+995", groups: [3, 2, 2, 2] },
  { iso: "DE", name: "Germany", dial: "+49", groups: [4, 7] },
  { iso: "GH", name: "Ghana", dial: "+233", groups: [2, 3, 4] },
  { iso: "GI", name: "Gibraltar", dial: "+350", groups: [8] },
  { iso: "GR", name: "Greece", dial: "+30", groups: [3, 3, 4] },
  { iso: "GL", name: "Greenland", dial: "+299", groups: [2, 2, 2] },
  { iso: "GD", name: "Grenada", dial: "+1", groups: [3, 3, 4] },
  { iso: "GP", name: "Guadeloupe", dial: "+590", groups: [3, 2, 2, 2] },
  { iso: "GU", name: "Guam", dial: "+1", groups: [3, 3, 4] },
  { iso: "GT", name: "Guatemala", dial: "+502", groups: [4, 4] },
  { iso: "GG", name: "Guernsey", dial: "+44", groups: [4, 6] },
  { iso: "GN", name: "Guinea", dial: "+224", groups: [3, 2, 2, 2] },
  { iso: "GW", name: "Guinea-Bissau", dial: "+245", groups: [3, 3, 3] },
  { iso: "GY", name: "Guyana", dial: "+592", groups: [3, 4] },
  { iso: "HT", name: "Haiti", dial: "+509", groups: [2, 2, 4] },
  { iso: "HN", name: "Honduras", dial: "+504", groups: [4, 4] },
  { iso: "HK", name: "Hong Kong SAR China", dial: "+852", groups: [4, 4] },
  { iso: "HU", name: "Hungary", dial: "+36", groups: [2, 3, 4] },
  { iso: "IS", name: "Iceland", dial: "+354", groups: [3, 4] },
  { iso: "IN", name: "India", dial: "+91", groups: [5, 5] },
  { iso: "ID", name: "Indonesia", dial: "+62", groups: [3, 3, 3] },
  { iso: "IR", name: "Iran", dial: "+98", groups: [3, 3, 4] },
  { iso: "IQ", name: "Iraq", dial: "+964", groups: [3, 3, 4] },
  { iso: "IE", name: "Ireland", dial: "+353", groups: [2, 3, 4] },
  { iso: "IM", name: "Isle of Man", dial: "+44", groups: [4, 6] },
  { iso: "IL", name: "Israel", dial: "+972", groups: [2, 3, 4] },
  { iso: "IT", name: "Italy", dial: "+39", groups: [3, 3, 4] },
  { iso: "JM", name: "Jamaica", dial: "+1", groups: [3, 3, 4] },
  { iso: "JP", name: "Japan", dial: "+81", groups: [2, 4, 4] },
  { iso: "JE", name: "Jersey", dial: "+44", groups: [4, 6] },
  { iso: "JO", name: "Jordan", dial: "+962", groups: [1, 4, 4] },
  { iso: "KZ", name: "Kazakhstan", dial: "+7", groups: [3, 3, 4] },
  { iso: "KE", name: "Kenya", dial: "+254", groups: [3, 6] },
  { iso: "KI", name: "Kiribati", dial: "+686", groups: [8] },
  { iso: "XK", name: "Kosovo", dial: "+383", groups: [2, 3, 3] },
  { iso: "KW", name: "Kuwait", dial: "+965", groups: [3, 5] },
  { iso: "KG", name: "Kyrgyzstan", dial: "+996", groups: [3, 3, 3] },
  { iso: "LA", name: "Laos", dial: "+856", groups: [2, 2, 3, 3] },
  { iso: "LV", name: "Latvia", dial: "+371", groups: [2, 3, 3] },
  { iso: "LB", name: "Lebanon", dial: "+961", groups: [2, 3, 3] },
  { iso: "LS", name: "Lesotho", dial: "+266", groups: [4, 4] },
  { iso: "LR", name: "Liberia", dial: "+231", groups: [2, 3, 4] },
  { iso: "LY", name: "Libya", dial: "+218", groups: [2, 7] },
  { iso: "LI", name: "Liechtenstein", dial: "+423", groups: [3, 3, 3] },
  { iso: "LT", name: "Lithuania", dial: "+370", groups: [3, 5] },
  { iso: "LU", name: "Luxembourg", dial: "+352", groups: [3, 3, 3] },
  { iso: "MO", name: "Macao SAR China", dial: "+853", groups: [4, 4] },
  { iso: "MG", name: "Madagascar", dial: "+261", groups: [2, 2, 3, 2] },
  { iso: "MW", name: "Malawi", dial: "+265", groups: [3, 2, 2, 2] },
  { iso: "MY", name: "Malaysia", dial: "+60", groups: [2, 3, 4] },
  { iso: "MV", name: "Maldives", dial: "+960", groups: [3, 4] },
  { iso: "ML", name: "Mali", dial: "+223", groups: [2, 2, 2, 2] },
  { iso: "MT", name: "Malta", dial: "+356", groups: [4, 4] },
  { iso: "MH", name: "Marshall Islands", dial: "+692", groups: [3, 4] },
  { iso: "MQ", name: "Martinique", dial: "+596", groups: [3, 2, 2, 2] },
  { iso: "MR", name: "Mauritania", dial: "+222", groups: [2, 2, 2, 2] },
  { iso: "MU", name: "Mauritius", dial: "+230", groups: [4, 4] },
  { iso: "YT", name: "Mayotte", dial: "+262", groups: [3, 2, 2, 2] },
  { iso: "MX", name: "Mexico", dial: "+52", groups: [3, 3, 4] },
  { iso: "FM", name: "Micronesia", dial: "+691", groups: [3, 4] },
  { iso: "MD", name: "Moldova", dial: "+373", groups: [3, 2, 3] },
  { iso: "MC", name: "Monaco", dial: "+377", groups: [1, 2, 2, 2, 2] },
  { iso: "MN", name: "Mongolia", dial: "+976", groups: [4, 4] },
  { iso: "ME", name: "Montenegro", dial: "+382", groups: [2, 3, 3] },
  { iso: "MS", name: "Montserrat", dial: "+1", groups: [3, 3, 4] },
  { iso: "MA", name: "Morocco", dial: "+212", groups: [1, 2, 2, 2, 2] },
  { iso: "MZ", name: "Mozambique", dial: "+258", groups: [2, 3, 4] },
  { iso: "MM", name: "Myanmar (Burma)", dial: "+95", groups: [1, 3, 4] },
  { iso: "NA", name: "Namibia", dial: "+264", groups: [2, 3, 4] },
  { iso: "NR", name: "Nauru", dial: "+674", groups: [3, 4] },
  { iso: "NP", name: "Nepal", dial: "+977", groups: [3, 7] },
  { iso: "NL", name: "Netherlands", dial: "+31", groups: [1, 8] },
  { iso: "NC", name: "New Caledonia", dial: "+687", groups: [2, 2, 2] },
  { iso: "NZ", name: "New Zealand", dial: "+64", groups: [2, 3, 4] },
  { iso: "NI", name: "Nicaragua", dial: "+505", groups: [4, 4] },
  { iso: "NE", name: "Niger", dial: "+227", groups: [2, 2, 2, 2] },
  { iso: "NG", name: "Nigeria", dial: "+234", groups: [3, 3, 4] },
  { iso: "NU", name: "Niue", dial: "+683", groups: [3, 4] },
  { iso: "NF", name: "Norfolk Island", dial: "+672", groups: [1, 5] },
  { iso: "KP", name: "North Korea", dial: "+850", groups: [3, 3, 4] },
  { iso: "MK", name: "North Macedonia", dial: "+389", groups: [2, 3, 3] },
  {
    iso: "MP",
    name: "Northern Mariana Islands",
    dial: "+1",
    groups: [3, 3, 4],
  },
  { iso: "NO", name: "Norway", dial: "+47", groups: [2, 2, 2, 2] },
  { iso: "OM", name: "Oman", dial: "+968", groups: [4, 4] },
  { iso: "PK", name: "Pakistan", dial: "+92", groups: [3, 7] },
  { iso: "PW", name: "Palau", dial: "+680", groups: [3, 4] },
  {
    iso: "PS",
    name: "Palestinian Territories",
    dial: "+970",
    groups: [3, 3, 3],
  },
  { iso: "PA", name: "Panama", dial: "+507", groups: [4, 4] },
  { iso: "PG", name: "Papua New Guinea", dial: "+675", groups: [4, 4] },
  { iso: "PY", name: "Paraguay", dial: "+595", groups: [3, 6] },
  { iso: "PE", name: "Peru", dial: "+51", groups: [3, 3, 3] },
  { iso: "PH", name: "Philippines", dial: "+63", groups: [3, 3, 4] },
  { iso: "PL", name: "Poland", dial: "+48", groups: [3, 3, 3] },
  { iso: "PT", name: "Portugal", dial: "+351", groups: [3, 3, 3] },
  { iso: "PR", name: "Puerto Rico", dial: "+1", groups: [3, 3, 4] },
  { iso: "QA", name: "Qatar", dial: "+974", groups: [4, 4] },
  { iso: "RE", name: "Réunion", dial: "+262", groups: [3, 2, 2, 2] },
  { iso: "RO", name: "Romania", dial: "+40", groups: [3, 3, 3] },
  { iso: "RU", name: "Russia", dial: "+7", groups: [3, 3, 2, 2] },
  { iso: "RW", name: "Rwanda", dial: "+250", groups: [3, 3, 3] },
  { iso: "WS", name: "Samoa", dial: "+685", groups: [2, 5] },
  { iso: "SM", name: "San Marino", dial: "+378", groups: [2, 2, 2, 2] },
  { iso: "ST", name: "São Tomé & Príncipe", dial: "+239", groups: [3, 4] },
  { iso: "SA", name: "Saudi Arabia", dial: "+966", groups: [2, 3, 4] },
  { iso: "SN", name: "Senegal", dial: "+221", groups: [2, 3, 2, 2] },
  { iso: "RS", name: "Serbia", dial: "+381", groups: [2, 7] },
  { iso: "SC", name: "Seychelles", dial: "+248", groups: [1, 3, 3] },
  { iso: "SL", name: "Sierra Leone", dial: "+232", groups: [2, 6] },
  { iso: "SG", name: "Singapore", dial: "+65", groups: [4, 4] },
  { iso: "SX", name: "Sint Maarten", dial: "+1", groups: [3, 3, 4] },
  { iso: "SK", name: "Slovakia", dial: "+421", groups: [3, 3, 3] },
  { iso: "SI", name: "Slovenia", dial: "+386", groups: [2, 3, 3] },
  { iso: "SB", name: "Solomon Islands", dial: "+677", groups: [2, 5] },
  { iso: "SO", name: "Somalia", dial: "+252", groups: [1, 7] },
  { iso: "ZA", name: "South Africa", dial: "+27", groups: [2, 3, 4] },
  { iso: "KR", name: "South Korea", dial: "+82", groups: [2, 4, 4] },
  { iso: "SS", name: "South Sudan", dial: "+211", groups: [3, 3, 3] },
  { iso: "ES", name: "Spain", dial: "+34", groups: [3, 2, 2, 2] },
  { iso: "LK", name: "Sri Lanka", dial: "+94", groups: [2, 3, 4] },
  { iso: "BL", name: "St. Barthélemy", dial: "+590", groups: [3, 2, 2, 2] },
  { iso: "SH", name: "St. Helena", dial: "+290", groups: [5] },
  { iso: "KN", name: "St. Kitts & Nevis", dial: "+1", groups: [3, 3, 4] },
  { iso: "LC", name: "St. Lucia", dial: "+1", groups: [3, 3, 4] },
  { iso: "MF", name: "St. Martin", dial: "+590", groups: [3, 2, 2, 2] },
  { iso: "PM", name: "St. Pierre & Miquelon", dial: "+508", groups: [2, 2, 2] },
  {
    iso: "VC",
    name: "St. Vincent & Grenadines",
    dial: "+1",
    groups: [3, 3, 4],
  },
  { iso: "SD", name: "Sudan", dial: "+249", groups: [2, 3, 4] },
  { iso: "SR", name: "Suriname", dial: "+597", groups: [3, 4] },
  {
    iso: "SJ",
    name: "Svalbard & Jan Mayen",
    dial: "+47",
    groups: [2, 2, 2, 2],
  },
  { iso: "SE", name: "Sweden", dial: "+46", groups: [2, 3, 2, 2] },
  { iso: "CH", name: "Switzerland", dial: "+41", groups: [2, 3, 2, 2] },
  { iso: "SY", name: "Syria", dial: "+963", groups: [3, 3, 3] },
  { iso: "TW", name: "Taiwan", dial: "+886", groups: [3, 3, 3] },
  { iso: "TJ", name: "Tajikistan", dial: "+992", groups: [2, 3, 4] },
  { iso: "TZ", name: "Tanzania", dial: "+255", groups: [3, 3, 3] },
  { iso: "TH", name: "Thailand", dial: "+66", groups: [2, 3, 4] },
  { iso: "TL", name: "Timor-Leste", dial: "+670", groups: [4, 4] },
  { iso: "TG", name: "Togo", dial: "+228", groups: [2, 2, 2, 2] },
  { iso: "TK", name: "Tokelau", dial: "+690", groups: [4] },
  { iso: "TO", name: "Tonga", dial: "+676", groups: [3, 4] },
  { iso: "TT", name: "Trinidad & Tobago", dial: "+1", groups: [3, 3, 4] },
  { iso: "TA", name: "Tristan da Cunha", dial: "+290", groups: [4] },
  { iso: "TN", name: "Tunisia", dial: "+216", groups: [2, 3, 3] },
  { iso: "TR", name: "Türkiye", dial: "+90", groups: [3, 3, 2, 2] },
  { iso: "TM", name: "Turkmenistan", dial: "+993", groups: [2, 6] },
  { iso: "TC", name: "Turks & Caicos Islands", dial: "+1", groups: [3, 3, 4] },
  { iso: "TV", name: "Tuvalu", dial: "+688", groups: [2, 4] },
  { iso: "VI", name: "U.S. Virgin Islands", dial: "+1", groups: [3, 3, 4] },
  { iso: "UG", name: "Uganda", dial: "+256", groups: [3, 6] },
  { iso: "UA", name: "Ukraine", dial: "+380", groups: [2, 3, 4] },
  { iso: "AE", name: "United Arab Emirates", dial: "+971", groups: [2, 3, 4] },
  { iso: "GB", name: "United Kingdom", dial: "+44", groups: [4, 6] },
  { iso: "US", name: "United States", dial: "+1", groups: [3, 3, 4] },
  { iso: "UY", name: "Uruguay", dial: "+598", groups: [2, 3, 3] },
  { iso: "UZ", name: "Uzbekistan", dial: "+998", groups: [2, 3, 2, 2] },
  { iso: "VU", name: "Vanuatu", dial: "+678", groups: [3, 4] },
  { iso: "VA", name: "Vatican City", dial: "+39", groups: [3, 3, 4] },
  { iso: "VE", name: "Venezuela", dial: "+58", groups: [3, 7] },
  { iso: "VN", name: "Vietnam", dial: "+84", groups: [3, 3, 3] },
  { iso: "WF", name: "Wallis & Futuna", dial: "+681", groups: [2, 2, 2] },
  { iso: "EH", name: "Western Sahara", dial: "+212", groups: [1, 2, 2, 2, 2] },
  { iso: "YE", name: "Yemen", dial: "+967", groups: [3, 3, 3] },
  { iso: "ZM", name: "Zambia", dial: "+260", groups: [2, 7] },
  { iso: "ZW", name: "Zimbabwe", dial: "+263", groups: [2, 3, 4] },
];

/** Countries with STEMSeeds chapters, shown first in pickers. */
export const chapterCountryCodes = [
  "US",
  "CA",
  "IN",
  "BD",
  "PH",
  "SE",
] as const;
