import type { FloatingPhotoSpec } from "@/components/ui/floating-photo";

export const heroCopy = {
  wordmark: "STEMSeeds",
  tagline: "Where Learning Takes Root",
  body: "A student-led nonprofit organization bringing hands-on STEM education to children of all backgrounds, including pediatric patients and underserved communities.",
  primaryCta: { label: "Start a Chapter", href: "/join-us" },
  secondaryCta: { label: "Donate", href: "/donate" },
} as const;

export const heroPhotos: FloatingPhotoSpec[] = [
  {
    src: "/images/stemseeds/stemseedspicture1.png",
    alt: "STEMSeeds students holding a Frisco certificate of recognition",
    depth: 0.55,
    rotate: -4.5,
    duration: 11,
    delay: 0.2,
    className:
      "top-[11%] left-[4%] hidden w-[168px] xl:left-[7%] xl:w-[190px] lg:block",
    width: 380,
    height: 480,
    sizes: "190px",
  },
  {
    src: "/images/stemseeds/stemseedspicture7.png",
    alt: "Two STEMSeeds chapter members in Bangladesh holding Where Learning Takes Root stickers",
    depth: 1.15,
    rotate: 3.8,
    duration: 9.5,
    delay: 0.6,
    className:
      "top-[8%] right-[5%] hidden w-[150px] xl:right-[8%] xl:w-[176px] lg:block",
    width: 360,
    height: 460,
    sizes: "176px",
  },
  {
    src: "/images/stemseeds/stemseedspicture4.png",
    alt: "Four STEMSeeds members delivering kits beside a Child Life cart in a children's hospital",
    depth: 0.85,
    rotate: 2.4,
    duration: 12.5,
    delay: 0.1,
    className:
      "top-[38%] left-[1.5%] hidden w-[158px] xl:left-[3.5%] xl:w-[178px] lg:block",
    width: 360,
    height: 470,
    sizes: "178px",
  },
  {
    src: "/images/stemseeds/stemseedspicture8.png",
    alt: "A STEMSeeds volunteer delivering kits with a Swedish Red Cross partner",
    depth: 1.45,
    rotate: -3.2,
    duration: 10.2,
    delay: 0.8,
    className:
      "top-[34%] right-[2%] hidden w-[170px] xl:right-[4%] xl:w-[196px] lg:block",
    width: 390,
    height: 500,
    sizes: "196px",
  },
  {
    src: "/images/stemseeds/stemseedspicture5.png",
    alt: "Two students unloading boxed STEM kits from a car trunk",
    depth: 0.7,
    rotate: -2.6,
    duration: 13,
    delay: 0.4,
    className:
      "bottom-[7%] left-[8%] hidden w-[176px] xl:left-[12%] xl:w-[200px] lg:block",
    width: 400,
    height: 500,
    sizes: "200px",
  },
  {
    src: "/images/stemseeds/stemseedspicture12.png",
    alt: "STEMSeeds members and a hospital staff member standing with a wagon of STEM kits",
    depth: 1.05,
    rotate: 4.2,
    duration: 8.8,
    delay: 0.3,
    className:
      "bottom-[6%] right-[7%] hidden w-[168px] xl:right-[11%] xl:w-[188px] lg:block",
    width: 380,
    height: 500,
    sizes: "188px",
  },
  {
    src: "/images/stemseeds/stemseedspicture4.png",
    alt: "Four STEMSeeds members delivering kits beside a Child Life cart in a children's hospital",
    depth: 0.35,
    rotate: -3.5,
    duration: 10,
    delay: 0,
    className: "top-2 left-[8%] w-[42%] max-w-[170px] lg:hidden",
    width: 320,
    height: 400,
    sizes: "42vw",
    mobile: true,
  },
  {
    src: "/images/stemseeds/stemseedspicture6.png",
    alt: "Two STEMSeeds members holding kits outside a Cook Children's clinic",
    depth: 0.6,
    rotate: 4,
    duration: 12,
    delay: 0.4,
    className: "top-0 right-[6%] w-[38%] max-w-[150px] lg:hidden",
    width: 300,
    height: 380,
    sizes: "38vw",
    mobile: true,
  },
  {
    src: "/images/stemseeds/stemseedspicture7.png",
    alt: "Two STEMSeeds chapter members in Bangladesh holding Where Learning Takes Root stickers",
    depth: 0.5,
    rotate: -2,
    duration: 9,
    delay: 0.2,
    className: "bottom-2 left-[18%] w-[36%] max-w-[140px] lg:hidden",
    width: 280,
    height: 360,
    sizes: "36vw",
    mobile: true,
  },
  {
    src: "/images/stemseeds/stemseedspicture12.png",
    alt: "STEMSeeds members and a hospital staff member standing with a wagon of STEM kits",
    depth: 0.75,
    rotate: 2.8,
    duration: 11.5,
    delay: 0.7,
    className: "bottom-0 right-[14%] w-[40%] max-w-[160px] lg:hidden",
    width: 320,
    height: 400,
    sizes: "40vw",
    mobile: true,
  },
];
